# Config file for automatic testing at travis-ci.org
language: python

python: 2.7

env:
  global:
    - secure: "I0GybBu84p7c5vMyZmlxZPAhcQEDguYYzjfKI2mY8yh1P6HkoBKSkYEvZT623K3m+CuJS++NVR9uOct1Cy9wmnQCAImKbDFU1wuD65vhGWdF1kEprME+ifz0r8FoUK/HpclOGZa9MBJvNXClc+KpFmLEbKB2y3QunPt4RH+yNQU="
  matrix:
    - TOX_ENV=py34
    - TOX_ENV=py33
    - TOX_ENV=py27
    - TOX_ENV=py26
    - TOX_ENV=pypy

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
